//! Core types for the strategy system.
//!
//! This module defines the Strategy trait and supporting types that all
//! strategy implementations must use.

use rust_decimal::Decimal;

/// Trading signal generated by a strategy.
///
/// Strategies return a Signal from their `on_tick()` method to indicate
/// the desired trading action.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Signal {
    /// Buy signal with the quantity to purchase.
    Buy { quantity: Decimal },
    /// Sell signal with the quantity to sell.
    Sell { quantity: Decimal },
    /// No action - hold current position.
    Hold,
}

/// Tick data provided to strategies for decision making.
///
/// Contains the essential market data from a single trade tick.
#[derive(Debug, Clone)]
pub struct StrategyTick {
    /// Trading symbol (e.g., "BTCUSDT").
    pub symbol: String,
    /// Trade price.
    pub price: Decimal,
    /// Trade quantity.
    pub quantity: Decimal,
    /// Unix timestamp in milliseconds.
    pub timestamp: i64,
}

/// Core trait that all trading strategies must implement.
///
/// Strategies process market ticks and generate trading signals.
/// They can maintain internal state (e.g., indicator values) and
/// support hot-reload of configuration.
///
/// # Thread Safety
///
/// Strategies must be `Send + Sync` to allow concurrent access
/// from multiple async tasks.
pub trait Strategy: Send + Sync {
    /// Process a tick and potentially generate a trading signal.
    ///
    /// Called for each market tick. The strategy may update its internal
    /// state (e.g., indicator values) and return a signal if conditions
    /// are met.
    ///
    /// # Arguments
    ///
    /// * `tick` - The market tick to process
    ///
    /// # Returns
    ///
    /// A trading signal indicating Buy, Sell, or Hold.
    fn on_tick(&mut self, tick: &StrategyTick) -> Signal;

    /// Update the strategy's configuration.
    ///
    /// Called when configuration is hot-reloaded. The strategy should
    /// validate the new configuration and apply it if valid.
    ///
    /// # Arguments
    ///
    /// * `config` - JSON value containing strategy-specific configuration
    ///
    /// # Returns
    ///
    /// Ok(()) if configuration was applied successfully, Err with
    /// description if configuration is invalid.
    fn update_config(&mut self, config: &serde_json::Value) -> Result<(), String>;

    /// Get the current internal state for debugging/monitoring.
    ///
    /// Returns a JSON representation of the strategy's internal state,
    /// useful for debugging and monitoring dashboards.
    fn get_state(&self) -> serde_json::Value;

    /// Get the strategy's identifier.
    ///
    /// Returns a static string identifying this strategy type.
    fn name(&self) -> &'static str;
}
