//! Risk engine actor with centralized risk management
//!
//! The RiskEngineActor processes all risk-related messages:
//! - `CheckOrder`: Synchronous risk check using oneshot response channel
//! - `PositionOpened`: Async notification when a position is opened
//! - `PositionClosed`: Async notification with P&L when position closes
//! - `PriceUpdate`: Real-time price for stop-loss monitoring
//! - `UpdateEquity`: Update portfolio equity
//! - `RegisterStrategy`: Register strategy-specific risk parameters
//! - `Shutdown`: Graceful shutdown request
//!
//! # Architecture
//!
//! The actor:
//! 1. Checks circuit breaker first (blocks all orders when halted)
//! 2. Looks up per-strategy risk parameters (falls back to global)
//! 3. Runs all RiskChecks in sequence (first rejection/scaling wins)
//! 4. Tracks open positions for stop-loss monitoring
//! 5. Emits StopLossEvent when stop-loss is triggered on price update
//!
//! # Phase Boundary
//!
//! StopLossEvent is sent via mpsc channel when stop-loss triggers. The receiver
//! (order executor) is implemented in Phase 06. This phase completes event
//! generation; Phase 06 wires the channel receiver to execute closing orders.

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::Serialize;
use tokio::sync::{mpsc, oneshot};
use tracing::{debug, error, info, warn};

use crate::data::OrderSide;
use crate::error::Error;
use crate::notifications::{AlertEvent, AlertSender, RiskEventType};
use crate::risk::checks::{MaxPositionSizeCheck, RiskCheck};
use crate::risk::circuit_breaker::{CircuitBreaker, TradingState};
use crate::risk::config::{GlobalRiskConfig, StrategyRiskOverrides, StrategyRiskParams};
use crate::risk::daily_loss::DailyLossLimitCheck;
use crate::risk::position::{OpenPosition, PositionTracker};
use crate::risk::types::{OrderRequest, PortfolioState, RiskDecision};

/// Event sent when stop-loss is triggered
///
/// **Phase boundary:** This event is generated by RiskEngine when stop-loss conditions
/// are met. The receiver (order executor) is implemented in Phase 06. The channel
/// sender is passed to RiskEngine at construction; Phase 06 will create the receiver
/// and wire it to the order execution system.
#[derive(Debug, Clone)]
pub struct StopLossEvent {
    pub order_id: String,
    pub symbol: String,
    pub side: OrderSide, // Side to close (opposite of position)
    pub quantity: Decimal,
    pub strategy_id: String,
}

/// Snapshot of current risk engine state for dashboard display
///
/// All fields serialize to JSON with Decimal values as strings (standard rust_decimal behavior).
#[derive(Debug, Clone, Serialize)]
pub struct RiskStateSnapshot {
    // Portfolio state
    /// Current total portfolio equity
    pub total_equity: Decimal,
    /// Profit/loss for current day
    pub daily_pnl: Decimal,
    /// High water mark (peak equity)
    pub peak_equity: Decimal,

    // Position limits
    /// Maximum position size as percentage of equity
    pub max_position_size_pct: Decimal,
    /// Current drawdown from peak as percentage (0-1)
    pub current_drawdown_pct: Decimal,
    /// Maximum allowed drawdown percentage
    pub max_drawdown_pct: Decimal,

    // Daily loss tracking
    /// Daily loss limit as percentage of equity
    pub daily_loss_limit_pct: Decimal,
    /// Current daily loss used as percentage of equity
    pub daily_loss_used_pct: Decimal,

    // Circuit breaker
    /// Status: "normal", "warning", or "triggered"
    pub circuit_breaker_status: String,
    /// When circuit breaker was triggered (if halted)
    pub circuit_breaker_triggered_at: Option<DateTime<Utc>>,

    // Position tracking
    /// Number of currently open positions
    pub open_positions: usize,
}

/// Configuration for RiskEngine
#[derive(Debug, Clone)]
pub struct RiskEngineConfig {
    pub initial_equity: Decimal,
    pub global_risk: GlobalRiskConfig,
    pub channel_capacity: usize,
}

impl Default for RiskEngineConfig {
    fn default() -> Self {
        Self {
            initial_equity: Decimal::new(100000, 0),       // 100000
            global_risk: GlobalRiskConfig {
                max_position_size_pct: Decimal::new(10, 2),  // 0.10
                stop_loss_pct: Decimal::new(2, 2),           // 0.02
                daily_loss_limit_pct: Decimal::new(5, 2),    // 0.05
                max_drawdown_pct: Decimal::new(15, 2),       // 0.15
            },
            channel_capacity: 1000,
        }
    }
}

/// Messages to the RiskEngine actor
#[derive(Debug)]
pub enum RiskMessage {
    /// Check if an order is allowed (synchronous response required)
    CheckOrder {
        /// Strategy that generated this order
        strategy_id: String,
        /// Trading pair symbol
        symbol: String,
        /// Buy or sell
        side: OrderSide,
        /// Requested quantity
        quantity: Decimal,
        /// Limit price (or market price for market orders)
        price: Decimal,
        /// Channel to send the risk decision back
        respond_to: oneshot::Sender<RiskDecision>,
    },

    /// Update position after fill (async, no response needed)
    PositionOpened {
        /// Strategy that owns this position
        strategy_id: String,
        /// Exchange order ID
        order_id: String,
        /// Trading pair symbol
        symbol: String,
        /// Buy (long) or Sell (short)
        side: OrderSide,
        /// Entry price
        entry_price: Decimal,
        /// Position size
        quantity: Decimal,
    },

    /// Update P&L after position closed
    PositionClosed {
        /// Exchange order ID being closed
        order_id: String,
        /// Realized profit/loss
        pnl: Decimal,
    },

    /// Current price update for stop-loss monitoring
    PriceUpdate {
        /// Trading pair symbol
        symbol: String,
        /// Current market price
        price: Decimal,
    },

    /// Update total equity (for position sizing calculations)
    UpdateEquity {
        /// New total equity value
        equity: Decimal,
    },

    /// Register strategy-specific risk parameters
    RegisterStrategy {
        /// Strategy identifier
        strategy_id: String,
        /// Risk parameter overrides for this strategy
        overrides: StrategyRiskOverrides,
    },

    /// Shutdown the actor gracefully
    Shutdown,

    /// Query current risk state (synchronous response required)
    QueryState {
        /// Channel to send the state snapshot back
        respond_to: oneshot::Sender<RiskStateSnapshot>,
    },
}

/// Handle for interacting with RiskEngine
///
/// This handle can be cloned and passed to multiple components that need
/// to interact with the risk engine. All methods are async-safe.
#[derive(Clone)]
pub struct RiskEngineHandle {
    sender: mpsc::Sender<RiskMessage>,
}

impl RiskEngineHandle {
    /// Create a new handle from a sender channel
    pub fn new(sender: mpsc::Sender<RiskMessage>) -> Self {
        Self { sender }
    }

    /// Check if order passes all risk controls (blocking call via oneshot)
    ///
    /// This is a synchronous operation from the caller's perspective -
    /// it waits for the RiskEngine to evaluate all risk checks and return
    /// a decision.
    ///
    /// # Returns
    ///
    /// - `Ok(RiskDecision::Approved)` - order passes all checks
    /// - `Ok(RiskDecision::Rejected { reason })` - order denied
    /// - `Ok(RiskDecision::Scaled { new_quantity, reason })` - order scaled down
    /// - `Err` - communication failure with risk engine
    pub async fn check_order(
        &self,
        strategy_id: &str,
        symbol: &str,
        side: OrderSide,
        quantity: Decimal,
        price: Decimal,
    ) -> Result<RiskDecision, Error> {
        let (tx, rx) = oneshot::channel();

        self.sender
            .send(RiskMessage::CheckOrder {
                strategy_id: strategy_id.to_string(),
                symbol: symbol.to_string(),
                side,
                quantity,
                price,
                respond_to: tx,
            })
            .await
            .map_err(|_| Error::Risk("RiskEngine channel closed".into()))?;

        rx.await
            .map_err(|_| Error::Risk("RiskEngine response channel closed".into()))
    }

    /// Notify the risk engine that a position was opened
    ///
    /// This is async (fire-and-forget) - the risk engine will track
    /// this position for stop-loss monitoring.
    pub async fn position_opened(
        &self,
        strategy_id: &str,
        order_id: &str,
        symbol: &str,
        side: OrderSide,
        entry_price: Decimal,
        quantity: Decimal,
    ) -> Result<(), Error> {
        self.sender
            .send(RiskMessage::PositionOpened {
                strategy_id: strategy_id.to_string(),
                order_id: order_id.to_string(),
                symbol: symbol.to_string(),
                side,
                entry_price,
                quantity,
            })
            .await
            .map_err(|_| Error::Risk("RiskEngine channel closed".into()))
    }

    /// Notify the risk engine that a position was closed
    ///
    /// The risk engine will update P&L tracking and remove the position
    /// from stop-loss monitoring.
    pub async fn position_closed(&self, order_id: &str, pnl: Decimal) -> Result<(), Error> {
        self.sender
            .send(RiskMessage::PositionClosed {
                order_id: order_id.to_string(),
                pnl,
            })
            .await
            .map_err(|_| Error::Risk("RiskEngine channel closed".into()))
    }

    /// Send a price update for stop-loss monitoring
    ///
    /// The risk engine will check all open positions for this symbol
    /// against their stop-loss prices.
    pub async fn price_update(&self, symbol: &str, price: Decimal) -> Result<(), Error> {
        self.sender
            .send(RiskMessage::PriceUpdate {
                symbol: symbol.to_string(),
                price,
            })
            .await
            .map_err(|_| Error::Risk("RiskEngine channel closed".into()))
    }

    /// Update total equity for position sizing calculations
    pub async fn update_equity(&self, equity: Decimal) -> Result<(), Error> {
        self.sender
            .send(RiskMessage::UpdateEquity { equity })
            .await
            .map_err(|_| Error::Risk("RiskEngine channel closed".into()))
    }

    /// Register strategy-specific risk parameters
    ///
    /// Overrides are merged with global defaults. Unspecified fields
    /// fall back to global configuration.
    pub async fn register_strategy(
        &self,
        strategy_id: &str,
        overrides: StrategyRiskOverrides,
    ) -> Result<(), Error> {
        self.sender
            .send(RiskMessage::RegisterStrategy {
                strategy_id: strategy_id.to_string(),
                overrides,
            })
            .await
            .map_err(|_| Error::Risk("RiskEngine channel closed".into()))
    }

    /// Request graceful shutdown of the risk engine
    pub async fn shutdown(&self) -> Result<(), Error> {
        self.sender
            .send(RiskMessage::Shutdown)
            .await
            .map_err(|_| Error::Risk("RiskEngine channel closed".into()))
    }

    /// Query current risk state (blocking call via oneshot)
    ///
    /// Returns a snapshot of the current risk engine state including:
    /// - Portfolio state (equity, daily P&L, peak equity)
    /// - Position limits and current drawdown
    /// - Daily loss tracking
    /// - Circuit breaker status
    /// - Open positions count
    pub async fn query_state(&self) -> Result<RiskStateSnapshot, Error> {
        let (tx, rx) = oneshot::channel();

        self.sender
            .send(RiskMessage::QueryState { respond_to: tx })
            .await
            .map_err(|_| Error::Risk("RiskEngine channel closed".into()))?;

        rx.await
            .map_err(|_| Error::Risk("RiskEngine response channel closed".into()))
    }
}

/// Internal actor state
struct RiskEngineActor {
    receiver: mpsc::Receiver<RiskMessage>,
    portfolio_state: PortfolioState,
    position_tracker: PositionTracker,
    circuit_breaker: CircuitBreaker,
    risk_checks: Vec<Box<dyn RiskCheck>>,
    strategy_params: HashMap<String, StrategyRiskParams>,
    global_config: GlobalRiskConfig,
    stop_loss_sender: Option<mpsc::Sender<StopLossEvent>>,
    /// Alert sender for risk notifications
    alert_sender: Option<AlertSender>,
}

impl RiskEngineActor {
    fn new(
        receiver: mpsc::Receiver<RiskMessage>,
        config: RiskEngineConfig,
        stop_loss_sender: Option<mpsc::Sender<StopLossEvent>>,
        alert_sender: Option<AlertSender>,
    ) -> Self {
        let portfolio_state = PortfolioState {
            total_equity: config.initial_equity,
            day_start_equity: config.initial_equity,
            daily_pnl: Decimal::ZERO,
        };

        let circuit_breaker = CircuitBreaker::new(
            config.initial_equity,
            config.global_risk.max_drawdown_pct,
        );

        // Register risk checks in priority order
        // DailyLossLimitCheck first (hard stop), then MaxPositionSizeCheck (can scale)
        let risk_checks: Vec<Box<dyn RiskCheck>> = vec![
            Box::new(DailyLossLimitCheck::new()),
            Box::new(MaxPositionSizeCheck::new()),
        ];

        Self {
            receiver,
            portfolio_state,
            position_tracker: PositionTracker::new(),
            circuit_breaker,
            risk_checks,
            strategy_params: HashMap::new(),
            global_config: config.global_risk,
            stop_loss_sender,
            alert_sender,
        }
    }

    /// Emit a risk alert if alert_sender is configured
    fn emit_risk_alert(&self, event_type: RiskEventType, message: impl Into<String>, symbol: Option<String>) {
        if let Some(ref sender) = self.alert_sender {
            let event = if let Some(sym) = symbol {
                AlertEvent::risk_with_symbol(event_type, message, sym)
            } else {
                AlertEvent::risk(event_type, message)
            };
            if !sender.try_send(event) {
                warn!("Failed to send risk alert (channel full)");
            }
        }
    }

    /// Emit a circuit breaker alert
    fn emit_circuit_breaker_alert(&self, message: impl Into<String>, drawdown_pct: Decimal) {
        if let Some(ref sender) = self.alert_sender {
            let event = AlertEvent::circuit_breaker(message, drawdown_pct);
            if !sender.try_send(event) {
                warn!("Failed to send circuit breaker alert (channel full)");
            }
        }
    }

    async fn run(mut self) {
        info!("RiskEngine actor started");

        while let Some(msg) = self.receiver.recv().await {
            match msg {
                RiskMessage::CheckOrder {
                    strategy_id,
                    symbol,
                    side,
                    quantity,
                    price,
                    respond_to,
                } => {
                    let decision = self.check_order(&strategy_id, &symbol, side, quantity, price);
                    let _ = respond_to.send(decision);
                }
                RiskMessage::PositionOpened {
                    strategy_id,
                    order_id,
                    symbol,
                    side,
                    entry_price,
                    quantity,
                } => {
                    self.on_position_opened(
                        &strategy_id,
                        &order_id,
                        &symbol,
                        side,
                        entry_price,
                        quantity,
                    );
                }
                RiskMessage::PositionClosed { order_id, pnl } => {
                    self.on_position_closed(&order_id, pnl);
                }
                RiskMessage::PriceUpdate { symbol, price } => {
                    self.on_price_update(&symbol, price).await;
                }
                RiskMessage::UpdateEquity { equity } => {
                    self.update_equity(equity);
                }
                RiskMessage::RegisterStrategy {
                    strategy_id,
                    overrides,
                } => {
                    self.register_strategy(&strategy_id, overrides);
                }
                RiskMessage::Shutdown => {
                    info!("RiskEngine shutdown requested");
                    break;
                }
                RiskMessage::QueryState { respond_to } => {
                    let snapshot = self.build_state_snapshot();
                    let _ = respond_to.send(snapshot);
                }
            }
        }

        info!(
            positions = self.position_tracker.len(),
            halted = self.circuit_breaker.is_halted(),
            "RiskEngine actor stopped"
        );
    }

    fn check_order(
        &mut self,
        strategy_id: &str,
        symbol: &str,
        side: OrderSide,
        quantity: Decimal,
        price: Decimal,
    ) -> RiskDecision {
        // Check circuit breaker first
        if self.circuit_breaker.is_halted() {
            return RiskDecision::Rejected {
                reason: "Trading halted: circuit breaker triggered".to_string(),
            };
        }

        // Get strategy-specific params (fallback to global)
        let params = self.get_strategy_params(strategy_id);

        let order = OrderRequest {
            strategy_id: strategy_id.to_string(),
            symbol: symbol.to_string(),
            side,
            quantity,
            price,
        };

        // Run all risk checks, return first rejection/scaling
        for check in &self.risk_checks {
            let decision = check.check(&order, &self.portfolio_state, &params);
            match decision {
                RiskDecision::Approved => continue,
                RiskDecision::Rejected { ref reason } => {
                    debug!(
                        check = check.name(),
                        decision = ?decision,
                        strategy_id,
                        symbol,
                        "Risk check triggered"
                    );

                    // Emit alert for daily limit reached
                    if check.name() == "DailyLossLimit" {
                        self.emit_risk_alert(
                            RiskEventType::DailyLimitReached,
                            reason.clone(),
                            None,
                        );
                    }

                    return decision;
                }
                RiskDecision::Scaled { .. } => {
                    debug!(
                        check = check.name(),
                        decision = ?decision,
                        strategy_id,
                        symbol,
                        "Risk check triggered"
                    );
                    return decision;
                }
            }
        }

        RiskDecision::Approved
    }

    fn on_position_opened(
        &mut self,
        strategy_id: &str,
        order_id: &str,
        symbol: &str,
        side: OrderSide,
        entry_price: Decimal,
        quantity: Decimal,
    ) {
        let params = self.get_strategy_params(strategy_id);

        let position = OpenPosition::new(
            order_id.to_string(),
            symbol.to_string(),
            side,
            entry_price,
            quantity,
            params.stop_loss_pct,
            strategy_id.to_string(),
        );

        debug!(
            order_id,
            symbol,
            entry_price = %entry_price,
            stop_loss_price = %position.stop_loss_price,
            "Position opened, tracking for stop-loss"
        );

        self.position_tracker.add(position);
    }

    fn on_position_closed(&mut self, order_id: &str, pnl: Decimal) {
        if let Some(position) = self.position_tracker.remove(order_id) {
            // Update daily P&L
            self.portfolio_state.daily_pnl = self
                .portfolio_state
                .daily_pnl
                .checked_add(pnl)
                .unwrap_or(self.portfolio_state.daily_pnl);

            // Update total equity
            self.portfolio_state.total_equity = self
                .portfolio_state
                .total_equity
                .checked_add(pnl)
                .unwrap_or(self.portfolio_state.total_equity);

            // Update circuit breaker
            self.circuit_breaker.update(self.portfolio_state.total_equity);

            debug!(
                order_id,
                symbol = %position.symbol,
                pnl = %pnl,
                total_equity = %self.portfolio_state.total_equity,
                daily_pnl = %self.portfolio_state.daily_pnl,
                "Position closed"
            );
        } else {
            warn!(order_id, "Position closed but not found in tracker");
        }
    }

    async fn on_price_update(&mut self, symbol: &str, price: Decimal) {
        // Check for stop-loss triggers
        let triggered = self.position_tracker.check_stop_losses(symbol, price);

        for position in triggered {
            warn!(
                order_id = %position.order_id,
                symbol = %position.symbol,
                entry_price = %position.entry_price,
                stop_price = %position.stop_loss_price,
                current_price = %price,
                "Stop-loss triggered"
            );

            // Emit stop-loss alert
            self.emit_risk_alert(
                RiskEventType::StopLossTriggered,
                format!("Stop-loss triggered for {} at {}", position.symbol, price),
                Some(position.symbol.clone()),
            );

            // Send stop-loss event if sender configured
            // Note: The receiver is created and wired in Phase 06 (Order Execution)
            if let Some(ref sender) = self.stop_loss_sender {
                let event = StopLossEvent {
                    order_id: position.order_id.clone(),
                    symbol: position.symbol.clone(),
                    side: position.closing_side(),
                    quantity: position.quantity,
                    strategy_id: position.strategy_id.clone(),
                };

                if let Err(e) = sender.send(event).await {
                    error!(
                        order_id = %position.order_id,
                        error = %e,
                        "Failed to send stop-loss event"
                    );
                }
            }

            // Remove position from tracker (it will be closed by order executor)
            self.position_tracker.remove(&position.order_id);
        }
    }

    fn update_equity(&mut self, equity: Decimal) {
        let was_halted = self.circuit_breaker.is_halted();
        self.portfolio_state.total_equity = equity;
        self.circuit_breaker.update(equity);

        // Emit circuit breaker alert if just triggered
        if !was_halted && self.circuit_breaker.is_halted() {
            let drawdown = self.circuit_breaker.calculate_drawdown(equity);
            let message = format!(
                "Circuit breaker triggered at {:.2}% drawdown",
                drawdown * Decimal::ONE_HUNDRED
            );
            self.emit_circuit_breaker_alert(message, drawdown);
        }

        debug!(
            equity = %equity,
            halted = self.circuit_breaker.is_halted(),
            "Equity updated"
        );
    }

    fn register_strategy(&mut self, strategy_id: &str, overrides: StrategyRiskOverrides) {
        let params = StrategyRiskParams::from_config(&self.global_config, &overrides);
        debug!(
            strategy_id,
            max_position_size_pct = %params.max_position_size_pct,
            stop_loss_pct = %params.stop_loss_pct,
            daily_loss_limit_pct = %params.daily_loss_limit_pct,
            "Strategy registered with risk params"
        );
        self.strategy_params.insert(strategy_id.to_string(), params);
    }

    fn get_strategy_params(&self, strategy_id: &str) -> StrategyRiskParams {
        self.strategy_params
            .get(strategy_id)
            .cloned()
            .unwrap_or_else(|| StrategyRiskParams::from_global(&self.global_config))
    }

    /// Build a snapshot of current risk state for API queries
    fn build_state_snapshot(&self) -> RiskStateSnapshot {
        let current_equity = self.portfolio_state.total_equity;
        let peak_equity = self.circuit_breaker.peak_equity();

        // Calculate current drawdown as percentage
        let current_drawdown_pct = self.circuit_breaker.calculate_drawdown(current_equity);

        // Calculate daily loss used as percentage
        // daily_loss_used = (day_start - current) / day_start if loss, else 0
        let daily_loss_used_pct = if self.portfolio_state.daily_pnl < Decimal::ZERO
            && !self.portfolio_state.day_start_equity.is_zero()
        {
            // daily_pnl is negative, so negate to get positive loss percentage
            (-self.portfolio_state.daily_pnl)
                .checked_div(self.portfolio_state.day_start_equity)
                .unwrap_or(Decimal::ZERO)
        } else {
            Decimal::ZERO
        };

        // Determine circuit breaker status
        // "triggered" = halted, "warning" = drawdown > 80% of max, "normal" otherwise
        let warning_threshold = self.global_config.max_drawdown_pct * Decimal::new(80, 2); // 80%
        let (circuit_breaker_status, circuit_breaker_triggered_at) = match self.circuit_breaker.state() {
            TradingState::Halted { triggered_at, .. } => {
                ("triggered".to_string(), Some(*triggered_at))
            }
            TradingState::Active => {
                if current_drawdown_pct >= warning_threshold {
                    ("warning".to_string(), None)
                } else {
                    ("normal".to_string(), None)
                }
            }
        };

        RiskStateSnapshot {
            total_equity: current_equity,
            daily_pnl: self.portfolio_state.daily_pnl,
            peak_equity,
            max_position_size_pct: self.global_config.max_position_size_pct,
            current_drawdown_pct,
            max_drawdown_pct: self.global_config.max_drawdown_pct,
            daily_loss_limit_pct: self.global_config.daily_loss_limit_pct,
            daily_loss_used_pct,
            circuit_breaker_status,
            circuit_breaker_triggered_at,
            open_positions: self.position_tracker.len(),
        }
    }
}

/// Start the RiskEngine actor
///
/// Returns a handle for sending messages. The actor runs in a background task.
///
/// # Arguments
///
/// * `config` - Configuration for initial equity and risk parameters
/// * `stop_loss_sender` - Optional channel for stop-loss events (receiver in Phase 06)
/// * `alert_sender` - Optional sender for risk notifications to AlertBroadcaster
///
/// # Example
///
/// ```ignore
/// use trading_bot::risk::engine::{start_risk_engine, RiskEngineConfig};
///
/// let handle = start_risk_engine(RiskEngineConfig::default(), None, None);
///
/// // Check if an order passes risk controls
/// let decision = handle.check_order("strategy-1", "BTCUSDT", OrderSide::Buy, dec!(1), dec!(50000)).await?;
/// ```
pub fn start_risk_engine(
    config: RiskEngineConfig,
    stop_loss_sender: Option<mpsc::Sender<StopLossEvent>>,
    alert_sender: Option<AlertSender>,
) -> RiskEngineHandle {
    let (sender, receiver) = mpsc::channel(config.channel_capacity);

    let actor = RiskEngineActor::new(receiver, config, stop_loss_sender, alert_sender);
    tokio::spawn(actor.run());

    RiskEngineHandle::new(sender)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rust_decimal_macros::dec;

    #[tokio::test]
    async fn test_risk_engine_handle_check_order() {
        let (tx, mut rx) = mpsc::channel(10);
        let handle = RiskEngineHandle::new(tx);

        // Spawn a mock receiver that always approves
        tokio::spawn(async move {
            if let Some(RiskMessage::CheckOrder { respond_to, .. }) = rx.recv().await {
                let _ = respond_to.send(RiskDecision::Approved);
            }
        });

        let result = handle
            .check_order("test-strategy", "BTCUSDT", OrderSide::Buy, dec!(1), dec!(50000))
            .await;

        assert!(result.is_ok());
        assert_eq!(result.unwrap(), RiskDecision::Approved);
    }

    #[tokio::test]
    async fn test_risk_engine_handle_position_opened() {
        let (tx, mut rx) = mpsc::channel(10);
        let handle = RiskEngineHandle::new(tx);

        let result = handle
            .position_opened(
                "test-strategy",
                "order-123",
                "BTCUSDT",
                OrderSide::Buy,
                dec!(50000),
                dec!(1),
            )
            .await;

        assert!(result.is_ok());

        // Verify the message was received
        let msg = rx.recv().await;
        assert!(matches!(msg, Some(RiskMessage::PositionOpened { .. })));
    }

    #[tokio::test]
    async fn test_risk_engine_handle_position_closed() {
        let (tx, mut rx) = mpsc::channel(10);
        let handle = RiskEngineHandle::new(tx);

        let result = handle.position_closed("order-123", dec!(500)).await;

        assert!(result.is_ok());

        let msg = rx.recv().await;
        assert!(matches!(msg, Some(RiskMessage::PositionClosed { .. })));
    }

    #[tokio::test]
    async fn test_risk_engine_handle_price_update() {
        let (tx, mut rx) = mpsc::channel(10);
        let handle = RiskEngineHandle::new(tx);

        let result = handle.price_update("BTCUSDT", dec!(51000)).await;

        assert!(result.is_ok());

        let msg = rx.recv().await;
        assert!(matches!(msg, Some(RiskMessage::PriceUpdate { .. })));
    }

    #[tokio::test]
    async fn test_risk_engine_handle_update_equity() {
        let (tx, mut rx) = mpsc::channel(10);
        let handle = RiskEngineHandle::new(tx);

        let result = handle.update_equity(dec!(105000)).await;

        assert!(result.is_ok());

        let msg = rx.recv().await;
        assert!(matches!(msg, Some(RiskMessage::UpdateEquity { .. })));
    }

    #[tokio::test]
    async fn test_risk_engine_handle_register_strategy() {
        let (tx, mut rx) = mpsc::channel(10);
        let handle = RiskEngineHandle::new(tx);

        let result = handle
            .register_strategy("conservative", StrategyRiskOverrides::default())
            .await;

        assert!(result.is_ok());

        let msg = rx.recv().await;
        assert!(matches!(msg, Some(RiskMessage::RegisterStrategy { .. })));
    }

    #[tokio::test]
    async fn test_risk_engine_handle_shutdown() {
        let (tx, mut rx) = mpsc::channel(10);
        let handle = RiskEngineHandle::new(tx);

        let result = handle.shutdown().await;

        assert!(result.is_ok());

        let msg = rx.recv().await;
        assert!(matches!(msg, Some(RiskMessage::Shutdown)));
    }

    #[tokio::test]
    async fn test_risk_engine_handle_channel_closed() {
        let (tx, rx) = mpsc::channel::<RiskMessage>(10);
        let handle = RiskEngineHandle::new(tx);

        // Drop receiver to close channel
        drop(rx);

        let result = handle
            .check_order("test", "BTCUSDT", OrderSide::Buy, dec!(1), dec!(50000))
            .await;

        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_risk_engine_config_default() {
        let config = RiskEngineConfig::default();
        assert_eq!(config.initial_equity, dec!(100000));
        assert_eq!(config.global_risk.max_position_size_pct, dec!(0.10));
        assert_eq!(config.global_risk.stop_loss_pct, dec!(0.02));
        assert_eq!(config.global_risk.daily_loss_limit_pct, dec!(0.05));
        assert_eq!(config.global_risk.max_drawdown_pct, dec!(0.15));
        assert_eq!(config.channel_capacity, 1000);
    }

    #[tokio::test]
    async fn test_start_risk_engine() {
        let handle = start_risk_engine(RiskEngineConfig::default(), None, None);

        // Should be able to check an order
        let decision = handle
            .check_order("test", "BTCUSDT", OrderSide::Buy, dec!(0.1), dec!(50000))
            .await
            .unwrap();

        // Small order should be approved (0.1 * 50000 = 5000 = 5% of 100k, within 10% limit)
        assert!(matches!(decision, RiskDecision::Approved));

        handle.shutdown().await.unwrap();
    }

    #[tokio::test]
    async fn test_risk_engine_scales_large_order() {
        let handle = start_risk_engine(RiskEngineConfig::default(), None, None);

        // Large order should be scaled (1 * 50000 = 50000 = 50% of 100k, exceeds 10% limit)
        let decision = handle
            .check_order("test", "BTCUSDT", OrderSide::Buy, dec!(1), dec!(50000))
            .await
            .unwrap();

        match decision {
            RiskDecision::Scaled { new_quantity, .. } => {
                // max_allowed = 100000 * 0.10 = 10000
                // scaled_quantity = 10000 / 50000 = 0.2
                assert_eq!(new_quantity, dec!(0.2));
            }
            _ => panic!("Expected Scaled decision, got {:?}", decision),
        }

        handle.shutdown().await.unwrap();
    }
}
