//! Backtest result and reporting types
//!
//! Defines the comprehensive result structure returned after backtest
//! completion, including all performance metrics, trade history,
//! and equity curve data.

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::Serialize;
use std::str::FromStr;

use super::metrics::TradeRecord;

/// Single point on the equity curve
#[derive(Debug, Clone, Serialize)]
pub struct EquityPoint {
    /// Timestamp of this equity snapshot
    pub timestamp: DateTime<Utc>,
    /// Total portfolio equity at this point
    pub equity: Decimal,
}

/// Comprehensive backtest result with all metrics
#[derive(Debug, Clone, Serialize)]
pub struct BacktestResult {
    // Configuration
    /// Trading pair symbol (e.g., "BTCUSDT")
    pub symbol: String,
    /// Name of the strategy being tested
    pub strategy_name: String,
    /// Backtest start time
    pub start_time: DateTime<Utc>,
    /// Backtest end time
    pub end_time: DateTime<Utc>,
    /// Starting capital in quote currency
    pub initial_capital: Decimal,

    // Execution settings
    /// Fee percentage used in simulation
    pub fee_pct: Decimal,
    /// Slippage percentage used in simulation
    pub slippage_pct: Decimal,

    // Summary metrics
    /// Final portfolio equity
    pub final_equity: Decimal,
    /// Total profit/loss (final_equity - initial_capital)
    pub total_pnl: Decimal,
    /// Total return as percentage (total_pnl / initial_capital)
    pub total_return_pct: Decimal,
    /// Total number of completed trades
    pub total_trades: u32,
    /// Number of profitable trades
    pub winning_trades: u32,
    /// Number of losing trades
    pub losing_trades: u32,
    /// Win rate (winning_trades / total_trades)
    pub win_rate: Decimal,

    // Risk metrics
    /// Maximum drawdown from peak to trough
    pub max_drawdown: Decimal,
    /// Sharpe ratio (risk-adjusted return)
    pub sharpe_ratio: Option<Decimal>,
    /// Sortino ratio (downside-adjusted return)
    pub sortino_ratio: Option<Decimal>,

    // Cost analysis
    /// Total fees paid across all trades
    pub total_fees_paid: Decimal,
    /// Total slippage cost across all trades
    pub total_slippage_cost: Decimal,

    // Tick statistics
    /// Total number of ticks processed
    pub total_ticks_processed: u64,
    /// Number of signals generated by strategy
    pub signals_generated: u32,

    // Optional detailed data (can be large)
    /// Complete trade history (if requested)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trades: Option<Vec<TradeRecord>>,
    /// Equity curve snapshots (if requested)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub equity_curve: Option<Vec<EquityPoint>>,
}

impl BacktestResult {
    /// Create a summary string for logging
    pub fn summary(&self) -> String {
        let hundred = Decimal::from_str("100").expect("valid decimal literal");
        format!(
            "Backtest {} on {}: {:.2}% return, {:.1}% win rate, {:.2}% max DD, {} trades",
            self.strategy_name,
            self.symbol,
            self.total_return_pct * hundred,
            self.win_rate * hundred,
            self.max_drawdown * hundred,
            self.total_trades
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rust_decimal_macros::dec;

    fn sample_result() -> BacktestResult {
        BacktestResult {
            symbol: "BTCUSDT".to_string(),
            strategy_name: "RSI".to_string(),
            start_time: DateTime::from_timestamp(1672531200, 0).unwrap(),
            end_time: DateTime::from_timestamp(1672617600, 0).unwrap(),
            initial_capital: dec!(10000),
            fee_pct: dec!(0.001),
            slippage_pct: dec!(0.0005),
            final_equity: dec!(10500),
            total_pnl: dec!(500),
            total_return_pct: dec!(0.05),
            total_trades: 20,
            winning_trades: 12,
            losing_trades: 8,
            win_rate: dec!(0.6),
            max_drawdown: dec!(0.08),
            sharpe_ratio: Some(dec!(1.5)),
            sortino_ratio: Some(dec!(2.1)),
            total_fees_paid: dec!(50),
            total_slippage_cost: dec!(25),
            total_ticks_processed: 100000,
            signals_generated: 40,
            trades: None,
            equity_curve: None,
        }
    }

    #[test]
    fn test_summary_format() {
        let result = sample_result();
        let summary = result.summary();

        assert!(summary.contains("RSI"));
        assert!(summary.contains("BTCUSDT"));
        assert!(summary.contains("5.00%")); // return
        assert!(summary.contains("60.0%")); // win rate
        assert!(summary.contains("8.00%")); // max drawdown
        assert!(summary.contains("20 trades"));
    }

    #[test]
    fn test_serialize_excludes_none_fields() {
        let result = sample_result();
        let json = serde_json::to_string(&result).unwrap();

        // trades and equity_curve should be absent when None
        assert!(!json.contains("\"trades\""));
        assert!(!json.contains("\"equity_curve\""));
    }

    #[test]
    fn test_serialize_includes_optional_fields() {
        let mut result = sample_result();
        result.trades = Some(vec![]);
        result.equity_curve = Some(vec![]);

        let json = serde_json::to_string(&result).unwrap();

        // Now they should be present
        assert!(json.contains("\"trades\""));
        assert!(json.contains("\"equity_curve\""));
    }

    #[test]
    fn test_equity_point_serialize() {
        let point = EquityPoint {
            timestamp: DateTime::from_timestamp(1672531200, 0).unwrap(),
            equity: dec!(10500),
        };

        let json = serde_json::to_string(&point).unwrap();
        assert!(json.contains("\"timestamp\""));
        assert!(json.contains("\"equity\""));
        assert!(json.contains("10500"));
    }
}
